#!/bin/sh

path="/home/ojornag/.config/eww"

song=$(playerctl metadata title -p spotify)
artist=$(playerctl metadata artist -p spotify)
album=$(playerctl metadata mpris:artUrl -p spotify)

string="  ${artist} - ${song}"

if [[ ${#string} -gt 40 ]]; then
	echo "${string:0:37}..."
else
	echo "${string}"
fi

status=$(playerctl status -p spotify)
if [[ $status = "Playing" ]]; then
	eww update playing=true
else
	eww update playing=false
fi

current=$(eww get current_album)
if [[ $current != "$song.jpeg" ]]; then
	rm $path/*.jpeg
	wget $album -P $path/ -O "$song.jpeg"
	magick "$path/$song.jpeg" -resize 400x400 "$path/$song.jpeg"
	eww update current_album="$song.jpeg"
fi
