local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.api.nvim_set_hl(0, "TelescopeNormal",  {bg="none"})
vim.api.nvim_set_hl(0, "TelescopeBorder",  {bg="none"})
vim.api.nvim_set_hl(0, "TelescopePromptNormal",  {bg="none"})
